# Generated by Django 5.2.1 on 2026-06-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0002_ingredient_order_status_userprofile_dishingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', '购物袋'), ('placed', '已下单'), ('ingredients_ready', '食材已备好'), ('cooking', '准备中'), ('done', '等抱抱')], default='draft', max_length=24),
        ),
    ]
