# Generated by Django 5.2.1 on 2026-06-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='visual_type',
        ),
    ]
